<?php

return [
    'blacklist' => [
        'chửi',
        'bậy',
        'địt',
        'kẹc',
        'cứt',
        'lồn',
        'buồi',
        'dái',
        'ngu',
        'óc chó',
        'fuck',
        'shit',
        'bitch',
        'whore',
        'asshole',
        'idiot',
        'dm',
        'vcl',
        'đcm',
        'đkm',
        'đậu má',
        'vãi',
        'chó chết',
        'cút',
        'khốn nạn',
        'mất dạy',
        'ngu ngốc',
        'óc bò',
    ],
];
